name: gibsonify
description: Collect nutritional data using Gibson's method.
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  uuid: ^3.0.5
  flutter_slidable: ^1.2.0
  gibsonify_api:
    path: packages/gibsonify_api
  gibsonify_repository:
    path: packages/gibsonify_repository
  geolocator: ^8.0.5
  dropdown_search: ^2.0.1
  intl_phone_field: ^3.0.1
  share_plus: ^3.0.5
  path_provider: ^2.0.9
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.20
  file_picker: ^4.4.0
  csv: ^5.0.1
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  bloc_test: ^9.0.2
  # TODO mocktail: ^0.1.4 or mockito???
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/ingredients/ingredients.json
    - assets/images/gibsonify_name_styled.png
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
