name: gibsonify
description: Collect nutritional data using Gibson's method.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dropdown_plus: ^0.0.9
  equatable: ^2.0.3  # TODO: see if can delete
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  formz: ^0.4.0 # TODO: see if can delete
  intl: ^0.17.0
  uuid: ^3.0.5  # TODO: see if can delete
  gibsonify_api:
    path: packages/gibsonify_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.2.0
  # TODO mocktail: ^0.1.4 or mockito???
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
