name: gibsonify
description: Collect nutritional data using Gibson's method.
publish_to: 'none'
version: 1.4.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  uuid: ^3.0.5
  flutter_slidable: ^2.0.0
  gibsonify_api:
    path: packages/gibsonify_api
  gibsonify_repository:
    path: packages/gibsonify_repository
  geolocator: ^9.0.2
  dropdown_search: ^5.0.3
  intl_phone_field: ^3.0.1
  share_plus: ^6.2.0
  path_provider: ^2.0.9
  package_info_plus: ^3.0.1
  url_launcher: ^6.0.20
  file_picker: ^5.2.2
  csv: ^5.0.1
  permission_handler: ^10.2.0
  cross_file: ^0.3.3
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  form_builder_phone_field: ^1.3.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.1.0
  flutter_p2p_connection:
    git:
      url: https://github.com/Archie-C/gibsonify_data_transfer.git
      ref: main
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  country_picker: ^2.0.19
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_map_tile_caching: ^6.2.0
  im_stepper: ^1.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  mockito: ^5.4.0

flutter:
  assets:
    - assets/ingredients/ingredients.json
    - assets/images/gibsonify_name_styled.png
    # FCT: IFCT2017
    - assets/fct/ifct2017/fct.json
    - assets/fct/ifct2017/photos/
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
