name: gibsonify_repository
description: Repository that handles requests for Gibson's form Collections and Recipes.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  gibsonify_api:
    path: ../gibsonify_api
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
