name: gibsonify_api
description: API that handles requests for Gibson's form Collections and Recipes.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  shared_preferences: ^2.0.9
  equatable: ^2.0.3
  uuid: ^3.0.5
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  latlong2: ^0.8.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.24.2
